logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity

spring:
    application:
        name: storage-server
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://127.0.0.1/seata-storage
        username: root
seata:
    enabled: true
    application-id: ${spring.application.name}
    # 需要和nacos中配置保持一致
    tx-service-group: hlos-group
    enable-auto-data-source-proxy: true
    config:
        type: nacos
        nacos:
            # 需要和server在同一个注册中心下
            serverAddr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
            group: SEATA_GROUP
            userName: ${SEATA_REGISTRY_NACOS_USERNAME:nacos}
            password: ${SEATA_REGISTRY_NACOS_PASSWORD:nacos}
    registry:
        type: nacos
        nacos:
            # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
            application: hlos-group
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
            group: SEATA_GROUP
            userName: ${SEATA_REGISTRY_NACOS_USERNAME:nacos}
            password: ${SEATA_REGISTRY_NACOS_PASSWORD:nacos}


